config/routes.rb
Rails.application.routes.draw do
  root 'sessions#new'
  resources :sessions, only: [:new, :create] do
    delete :sign_out, on: :collection
  end

  resources :users, only: [:show, :edit, :update]

  resources :companies, only: [:show, :edit, :update]

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/company.rb
class Company < ApplicationRecord
  audited
  has_associated_audits
  
  has_many :departments, dependent: :destroy
  has_many :users, through: :departments

  validates_presence_of :name

  def top_employees
    departments.joins(
      <<~SQL
        join lateral (
        select * from users
        where department_id = departments.id
        order by salary desc
        limit 3
        ) u on true
      SQL
    ).order(:name).select('departments.*, u.*')
  end
end

app/models/department.rb
class Department < ApplicationRecord
  audited associated_with: :company

  belongs_to :company
  has_many   :users, dependent: :destroy

  validates_presence_of :name
end

app/models/user.rb
class User < ApplicationRecord
  has_secure_password
  audited associated_with: :company

  belongs_to :department
  delegate :company, to: :department

  validates_presence_of :first_name, :last_name, :phone, :address,
                        :email, :salary, :bonus, :role
  validates :phone, length: { is: 10 }
  validates :email, format: { with: URI::MailTo::EMAIL_REGEXP }
  validates :password, length: { minimum: 8 }, on: :create
  validates :password, length: { minimum: 8 }, allow_nil: true, on: :update

  before_validation :format_phone_number

  def format_phone_number
    phone&.gsub!(/\D/, '')
  end

  enum role: {
    employee:      10,
    administrator: 20
  }

  def full_name
    "#{first_name} #{last_name}"
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  include Pundit

  after_action :verify_authorized, unless: :sessions_controller?

  rescue_from Pundit::NotAuthorizedError, with: :user_not_authorized

  private

  def current_user
    @current_user ||= User.find_by id: session[:current_user_id]
  end
  helper_method :current_user

  def user_not_authorized
    render file: "#{Rails.public_path}/404.html" , status: :not_found
  end

  def sessions_controller?
    controller_name == 'sessions'
  end
end

app/controllers/companies_controller.rb
class CompaniesController < ApplicationController
  before_action :load_resource, only: [:show, :edit, :update]

  def show
  end

  def edit
  end

  def update
    if @company.update permitted_attributes(@company)
      redirect_to @company, notice: 'Company updated successfully'
    else
      render :edit
    end
  end

  private

  def load_resource
    @company = Company.find_by id: params[:id]
    authorize @company
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  def new
    @users = User.joins(department: :company)
      .order('companies.name, users.role desc')
      .group_by { |user| user.company.name }
  end

  def create
    session[:current_user_id] = params[:user_id]

    if current_user
      redirect_to current_user
    else
      redirect_to :new_session
    end
  end

  def sign_out
    session[:current_user_id] = nil
    redirect_to :new_session
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :load_resource, only: [:show, :edit, :update]

  def show
  end

  def edit
  end

  def update
    if @user.update user_params
      redirect_to @user, notice: 'Profile updated successfully'
    else
      render :edit
    end
  end

  private

  def load_resource
    @user = User.find_by id: params[:id]
    authorize @user
  end

  def user_params
    permitted_params = permitted_attributes @user

    unless params[:user][:password].present?
      permitted_params.delete(:password)
      permitted_params.delete(:password_confirmation)
    end

    permitted_params
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/companies/_form.html.erb
<%= form_with(model: company, local: true) do |form| %>
  <% if company.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(company.errors.count, "error") %> prohibited this company from being saved:</h2>

      <ul>
      <% company.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/companies/edit.html.erb
<h1>Edit Company</h1>
<br>

<%= render 'form', company: @company %>

<%= link_to 'Return to Company Profile', @company %>

app/views/companies/show.html.erb
<%= link_to 'Employee Profile', current_user %>

<p id="notice"><%= notice %></p>

<h1>Company Profile</h1>
<br>

<p>
  <strong>Name:</strong>
  <%= @company.name %>
</p>

<%= link_to 'Edit Company', edit_company_path(@company) %>

<p><strong>Top Earning Employees:</strong></p>

<table>
  <thead>
    <tr>
      <th>Department</th>
      <th>Name</th>
      <th>Top Salaries</th>
    </tr>
  </thead>

  <tbody>
    <% @company.top_employees.each do |department_user| %>
      <% user = User.new first_name: department_user.first_name, last_name: department_user.last_name, salary: department_user.salary %>
      <tr>
        <td><%= department_user.name %></td>
        <td><%= user.full_name %></td>
        <td><%= number_to_currency user.salary, precision: 0 %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<p><strong>All Employees:</strong></p>

<table>
  <thead>
    <tr>
      <th>Department</th>
      <th>Name</th>
      <th>Email</th>
      <th>Phone</th>
      <th>Address</th>
      <th>Salary</th>
      <th>Bonus</th>
      <th colspan="2"></th>
    </tr>
  </thead>

  <tbody>
    <% @company.users.order(:last_name).each do |user| %>
      <tr>
        <td><%= user.department.name %></td>
        <td><%= user.full_name %></td>
        <td><%= user.email %></td>
        <td><%= number_to_phone user.phone %></td>
        <td><%= user.address %></td>
        <td><%= number_to_currency user.salary, precision: 0 %></td>
        <td><%= number_to_currency user.bonus, precision: 0 %></td>
        <td><%= link_to 'Show', user %></td>
        <td><%= link_to 'Edit', edit_user_path(user) %></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>PatientIq</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <% if current_user && !response.not_found? %>
      <%= form_tag sign_out_sessions_path, method: :delete do %>
        <%= submit_tag 'Logout' %>
      <% end %>
    <% end %>

    <%= yield %>
  </body>
</html>

app/views/users/_form.html.erb
<% permitted_attributes = policy(user).permitted_attributes %>

<%= form_with(model: user, local: true) do |form| %>
  <% if user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% user.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <p>
    <strong>Name:</strong>
    <%= @user.full_name %>
  </p>

  <p>
    <strong>Role:</strong>
    <%= @user.role.humanize %>
  </p>

  <% if permitted_attributes.include?(:department_id) %>
    <div class="field">
      <%= form.label :department_id %>
      <%= form.select :department_id, user.company.departments.map { |department| [department.name, department.id] } %>
    </div>
  <% else %>
    <p>
      <strong>Department:</strong>
      <%= @user.department.name %>
    </p>
  <% end %>

  <% if permitted_attributes.include?(:phone) %>
    <div class="field">
      <%= form.label :phone %>
      <%= form.text_field :phone %>
    </div>
  <% else %>
    <p>
      <strong>Phone:</strong>
      <%= number_to_phone @user.phone %>
    </p>
  <% end %>

  <% if permitted_attributes.include?(:address) %>
    <div class="field">
      <%= form.label :address %>
      <%= form.text_area :address %>
    </div>
  <% else %>
    <p>
      <strong>Phone:</strong>
      <%= number_to_phone @user.phone %>
    </p>
  <% end %>

  <% if permitted_attributes.include?(:email) %>
    <div class="field">
      <%= form.label :email %>
      <%= form.text_field :email %>
    </div>
  <% else %>
    <p>
      <strong>Email:</strong>
      <%= @user.email %>
    </p>
  <% end %>

  <% if permitted_attributes.include?(:password) %>
    <div class="field">
      <%= form.label :password %>
      <%= form.password_field :password %>
    </div>
  <% end %>

  <% if permitted_attributes.include?(:password_confirmation) %>
    <div class="field">
      <%= form.label :password_confirmation %>
      <%= form.password_field :password_confirmation %>
    </div>
  <% end %>

  <% if permitted_attributes.include?(:salary) %>
    <div class="field">
      <%= form.label :salary %>
      <%= form.number_field :salary %>
    </div>
  <% else %>
    <p>
      <strong>Salary:</strong>
      <%= number_to_currency @user.salary, precision: 0 %>
    </p>
  <% end %>

  <% if permitted_attributes.include?(:bonus) %>
    <div class="field">
      <%= form.label :bonus %>
      <%= form.number_field :bonus %>
    </div>
  <% else %>
    <p>
      <strong>Bonus:</strong>
      <%= number_to_currency @user.bonus, precision: 0 %>
    </p>
  <% end %>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/users/edit.html.erb
<h1>Edit Profile</h1>
<br>

<%= render 'form', user: @user %>

<%= link_to 'Return to Employee Profile', @user %>

app/views/users/show.html.erb
<% if policy(@user.company).show? %>
  <%= link_to 'Company Profile', company_path(@user.company) %>
<% end %>

<p id="notice"><%= notice %></p>

<h1>Employee Profile</h1>
<br>

<p>
  <strong>Name:</strong>
  <%= @user.full_name %>
</p>

<p>
  <strong>Role:</strong>
  <%= @user.role.humanize %>
</p>

<p>
  <strong>Department:</strong>
  <%= @user.department.name %>
</p>

<p>
  <strong>Email:</strong>
  <%= @user.email %>
</p>

<p>
  <strong>Phone:</strong>
  <%= number_to_phone @user.phone %>
</p>

<p>
  <strong>Address:</strong>
  <%= @user.address %>
</p>

<p>
  <strong>Salary:</strong>
  <%= number_to_currency @user.salary, precision: 0 %>
</p>

<p>
  <strong>Bonus:</strong>
  <%= number_to_currency @user.bonus, precision: 0 %>
</p>

<%= link_to 'Edit Profile', edit_user_path(@user) %>